name: Sync tmog cask

on:
  schedule:
    - cron: "42 0,6,12,18 * * *"
  workflow_dispatch:

jobs:
  sync:
    permissions:
      contents: write
    uses: ./.github/workflows/_sync-cask.yml
    with:
      cask: tmog
