name: Sync inshellisense-rounded cask

on:
  schedule:
    - cron: "21 5 * * *"
  workflow_dispatch:

jobs:
  sync:
    permissions:
      contents: write
    uses: ./.github/workflows/_sync-cask.yml
    with:
      cask: inshellisense-rounded
      package_kind: formula
      package_path: Formula/inshellisense-rounded.rb
